"""0005 content

Revision ID: 1d09425f2a28
Revises: f8e77c101179
Create Date: 2026-09-06 18:53:18.327911
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

_T = ["topics", "entities", "content_items", "content_scores"]

revision: str = '1d09425f2a28'
down_revision: str | None = 'f8e77c101179'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('project_id', 'normalized', name='uq_entities_project_norm')
    )
    op.create_index(op.f('ix_entities_project_id'), 'entities', ['project_id'], unique=False)
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_table('topics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('pillar_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_topics_project_slug')
    )
    op.create_index(op.f('ix_topics_pillar_id'), 'topics', ['pillar_id'], unique=False)
    op.create_index(op.f('ix_topics_project_id'), 'topics', ['project_id'], unique=False)
    op.create_index(op.f('ix_topics_tenant_id'), 'topics', ['tenant_id'], unique=False)
    op.create_table('content_items',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('canonical_target', sa.Text(), nullable=True),
    sa.Column('primary_keyword_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_content_items_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items')),
    sa.UniqueConstraint('project_id', 'url_hash', name='uq_content_items_project_url')
    )
    op.create_index(op.f('ix_content_items_primary_keyword_id'), 'content_items', ['primary_keyword_id'], unique=False)
    op.create_index(op.f('ix_content_items_project_id'), 'content_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_items_tenant_id'), 'content_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_content_items_topic_id'), 'content_items', ['topic_id'], unique=False)
    op.create_index('ix_content_items_type', 'content_items', ['project_id', 'content_type'], unique=False)
    op.create_table('content_scores',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('scorer', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('fk_content_scores_content_item_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_scores'))
    )
    op.create_index('ix_content_scores_item', 'content_scores', ['content_item_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_content_scores_project_id'), 'content_scores', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_scores_tenant_id'), 'content_scores', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for t in _T:
        rls_enable(t, project_scoped=True)


def downgrade() -> None:
    for t in _T:
        op.execute(f"DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}")
        op.execute(f"ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_scores_tenant_id'), table_name='content_scores')
    op.drop_index(op.f('ix_content_scores_project_id'), table_name='content_scores')
    op.drop_index('ix_content_scores_item', table_name='content_scores')
    op.drop_table('content_scores')
    op.drop_index('ix_content_items_type', table_name='content_items')
    op.drop_index(op.f('ix_content_items_topic_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_tenant_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_project_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_primary_keyword_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_topics_tenant_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_project_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_pillar_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_project_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
