"""0008 safety spine

Revision ID: 246f989c583e
Revises: 923521d86e85
Create Date: 2026-09-06 19:06:37.757850
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = '246f989c583e'
down_revision: str | None = '923521d86e85'
branch_labels: str | Sequence[str] | None = None
_T = ["plans", "plan_steps", "approvals", "changes", "change_versions", "verifications", "rollbacks", "incidents", "agent_decisions"]
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_id', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('model_role', sa.String(length=16), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=True),
    sa.Column('tool_versions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_decisions'))
    )
    op.create_index(op.f('ix_agent_decisions_correlation_id'), 'agent_decisions', ['correlation_id'], unique=False)
    op.create_index('ix_agent_decisions_kind', 'agent_decisions', ['project_id', 'kind'], unique=False)
    op.create_index(op.f('ix_agent_decisions_project_id'), 'agent_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_tenant_id'), 'agent_decisions', ['tenant_id'], unique=False)
    op.create_table('changes',
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('plan_step_id', sa.UUID(), nullable=True),
    sa.Column('adapter', sa.String(length=24), nullable=False),
    sa.Column('action_class', sa.String(length=28), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('pre_state_hash', sa.String(length=64), nullable=True),
    sa.Column('rollback_strategy', sa.String(length=24), nullable=False),
    sa.Column('backup_ref', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('side_effect_key', sa.String(length=80), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_changes')),
    sa.UniqueConstraint('side_effect_key', name='uq_changes_side_effect_key')
    )
    op.create_index('ix_changes_plan', 'changes', ['plan_id'], unique=False)
    op.create_index(op.f('ix_changes_plan_id'), 'changes', ['plan_id'], unique=False)
    op.create_index(op.f('ix_changes_project_id'), 'changes', ['project_id'], unique=False)
    op.create_index(op.f('ix_changes_tenant_id'), 'changes', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_change_id'), 'incidents', ['change_id'], unique=False)
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('change_versions',
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], name=op.f('fk_change_versions_change_id_changes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_versions'))
    )
    op.create_index(op.f('ix_change_versions_change_id'), 'change_versions', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_versions_project_id'), 'change_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_change_versions_tenant_id'), 'change_versions', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('chosen_solution', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('max_action_class', sa.String(length=28), nullable=False),
    sa.Column('agent_decision_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_plans_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_opportunity_id'), 'plans', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_plans_project_id'), 'plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('rollbacks',
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], name=op.f('fk_rollbacks_change_id_changes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rollbacks'))
    )
    op.create_index(op.f('ix_rollbacks_change_id'), 'rollbacks', ['change_id'], unique=False)
    op.create_index(op.f('ix_rollbacks_project_id'), 'rollbacks', ['project_id'], unique=False)
    op.create_index(op.f('ix_rollbacks_tenant_id'), 'rollbacks', ['tenant_id'], unique=False)
    op.create_table('verifications',
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], name=op.f('fk_verifications_change_id_changes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    op.create_index(op.f('ix_verifications_change_id'), 'verifications', ['change_id'], unique=False)
    op.create_index(op.f('ix_verifications_project_id'), 'verifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_verifications_tenant_id'), 'verifications', ['tenant_id'], unique=False)
    op.create_table('approvals',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_approvals_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_plan_id'), 'approvals', ['plan_id'], unique=False)
    op.create_index(op.f('ix_approvals_project_id'), 'approvals', ['project_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('plan_steps',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('tool_version', sa.String(length=20), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('action_class', sa.String(length=28), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('rollback', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_steps_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_steps')),
    sa.UniqueConstraint('plan_id', 'ordinal', name='uq_plan_steps_plan_ordinal')
    )
    op.create_index(op.f('ix_plan_steps_plan_id'), 'plan_steps', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_steps_project_id'), 'plan_steps', ['project_id'], unique=False)
    op.create_index(op.f('ix_plan_steps_tenant_id'), 'plan_steps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for t in _T:
        rls_enable(t, project_scoped=True)


def downgrade() -> None:
    for t in _T:
        op.execute(f'DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}')
        op.execute(f'ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {t} DISABLE ROW LEVEL SECURITY')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_steps_tenant_id'), table_name='plan_steps')
    op.drop_index(op.f('ix_plan_steps_project_id'), table_name='plan_steps')
    op.drop_index(op.f('ix_plan_steps_plan_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_project_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_plan_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_verifications_tenant_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_project_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_change_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_rollbacks_tenant_id'), table_name='rollbacks')
    op.drop_index(op.f('ix_rollbacks_project_id'), table_name='rollbacks')
    op.drop_index(op.f('ix_rollbacks_change_id'), table_name='rollbacks')
    op.drop_table('rollbacks')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_project_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_opportunity_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_change_versions_tenant_id'), table_name='change_versions')
    op.drop_index(op.f('ix_change_versions_project_id'), table_name='change_versions')
    op.drop_index(op.f('ix_change_versions_change_id'), table_name='change_versions')
    op.drop_table('change_versions')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_change_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_changes_tenant_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_project_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_plan_id'), table_name='changes')
    op.drop_index('ix_changes_plan', table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_agent_decisions_tenant_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_project_id'), table_name='agent_decisions')
    op.drop_index('ix_agent_decisions_kind', table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_correlation_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
