"""0003 seo_issues

Revision ID: 29338c6c7573
Revises: bb27d509590e
Create Date: 2026-09-06 18:21:12.033838
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = '29338c6c7573'
down_revision: str | None = 'bb27d509590e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_issues',
    sa.Column('crawl_run_id', sa.UUID(), nullable=True),
    sa.Column('check_code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_pattern', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('fix', sa.Text(), nullable=True),
    sa.Column('normalized_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_issues')),
    sa.UniqueConstraint('project_id', 'normalized_key', name='uq_seo_issues_project_key')
    )
    op.create_index(op.f('ix_seo_issues_check_code'), 'seo_issues', ['check_code'], unique=False)
    op.create_index(op.f('ix_seo_issues_crawl_run_id'), 'seo_issues', ['crawl_run_id'], unique=False)
    op.create_index('ix_seo_issues_open', 'seo_issues', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_seo_issues_project_id'), 'seo_issues', ['project_id'], unique=False)
    op.create_index('ix_seo_issues_project_sev', 'seo_issues', ['project_id', 'severity'], unique=False)
    op.create_index(op.f('ix_seo_issues_tenant_id'), 'seo_issues', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    rls_enable("seo_issues", project_scoped=True)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS seo_issues_tenant_isolation ON seo_issues")
    op.execute("ALTER TABLE seo_issues NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE seo_issues DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_issues_tenant_id'), table_name='seo_issues')
    op.drop_index('ix_seo_issues_project_sev', table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_project_id'), table_name='seo_issues')
    op.drop_index('ix_seo_issues_open', table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_crawl_run_id'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_check_code'), table_name='seo_issues')
    op.drop_table('seo_issues')
    # ### end Alembic commands ###
