"""0009 analytics

Revision ID: 3f086c93a575
Revises: 246f989c583e
Create Date: 2026-09-06 19:48:52.613874
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = '3f086c93a575'
down_revision: str | None = '246f989c583e'
branch_labels: str | Sequence[str] | None = None
_T = ["metric_snapshots", "anomalies", "experiments", "learnings", "opportunity_weights", "memory_entries"]
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('metric', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_ref', sa.String(length=120), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('magnitude_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('baseline', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('observed', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('z_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('investigation', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    op.create_index(op.f('ix_anomalies_project_id'), 'anomalies', ['project_id'], unique=False)
    op.create_index(op.f('ix_anomalies_tenant_id'), 'anomalies', ['tenant_id'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_type', sa.String(length=24), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('primary_metric', sa.String(length=24), nullable=False),
    sa.Column('metric_definitions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('baseline_start', sa.Date(), nullable=False),
    sa.Column('baseline_end', sa.Date(), nullable=False),
    sa.Column('treatment_start', sa.Date(), nullable=False),
    sa.Column('measurement_window_days', sa.Integer(), nullable=False),
    sa.Column('control', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('methodology', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confounders', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_change_id'), 'experiments', ['change_id'], unique=False)
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)
    op.create_index(op.f('ix_experiments_tenant_id'), 'experiments', ['tenant_id'], unique=False)
    op.create_table('learnings',
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=40), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_delta', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('methodology_note', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learnings'))
    )
    op.create_index(op.f('ix_learnings_opportunity_type'), 'learnings', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_learnings_project_id'), 'learnings', ['project_id'], unique=False)
    op.create_index(op.f('ix_learnings_source_id'), 'learnings', ['source_id'], unique=False)
    op.create_index(op.f('ix_learnings_tenant_id'), 'learnings', ['tenant_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_entries'))
    )
    op.create_index('ix_memory_entries_kind', 'memory_entries', ['project_id', 'kind'], unique=False)
    op.create_index(op.f('ix_memory_entries_project_id'), 'memory_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_tenant_id'), 'memory_entries', ['tenant_id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('metric', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_ref', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots')),
    sa.UniqueConstraint('project_id', 'metric', 'scope', 'scope_ref', 'date', name='uq_metric_snapshots_key')
    )
    op.create_index('ix_metric_snapshots_metric_date', 'metric_snapshots', ['project_id', 'metric', 'date'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_project_id'), 'metric_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_tenant_id'), 'metric_snapshots', ['tenant_id'], unique=False)
    op.create_table('opportunity_weights',
    sa.Column('opportunity_type', sa.String(length=40), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('updated_from_learning', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_weights')),
    sa.UniqueConstraint('project_id', 'opportunity_type', name='uq_opportunity_weights_type')
    )
    op.create_index(op.f('ix_opportunity_weights_project_id'), 'opportunity_weights', ['project_id'], unique=False)
    op.create_index(op.f('ix_opportunity_weights_tenant_id'), 'opportunity_weights', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for t in _T:
        rls_enable(t, project_scoped=True)


def downgrade() -> None:
    for t in _T:
        op.execute(f'DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}')
        op.execute(f'ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {t} DISABLE ROW LEVEL SECURITY')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_weights_tenant_id'), table_name='opportunity_weights')
    op.drop_index(op.f('ix_opportunity_weights_project_id'), table_name='opportunity_weights')
    op.drop_table('opportunity_weights')
    op.drop_index(op.f('ix_metric_snapshots_tenant_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_project_id'), table_name='metric_snapshots')
    op.drop_index('ix_metric_snapshots_metric_date', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_memory_entries_tenant_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_project_id'), table_name='memory_entries')
    op.drop_index('ix_memory_entries_kind', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_learnings_tenant_id'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_source_id'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_project_id'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_opportunity_type'), table_name='learnings')
    op.drop_table('learnings')
    op.drop_index(op.f('ix_experiments_tenant_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_change_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_anomalies_tenant_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_project_id'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
