"""0006 knowledge graph

Revision ID: 8237b61bf68a
Revises: 1d09425f2a28
Create Date: 2026-09-06 18:56:32.538904
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

_T = ["kg_nodes", "kg_edges", "embeddings"]
_TENANT = ["embedding_jobs"]

revision: str = '8237b61bf68a'
down_revision: str | None = '1d09425f2a28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_jobs'))
    )
    op.create_index(op.f('ix_embedding_jobs_project_id'), 'embedding_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_tenant_id'), 'embedding_jobs', ['tenant_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('owner_type', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('owner_type', 'owner_id', 'model', 'model_version', name='uq_embeddings_owner_model')
    )
    op.create_index(op.f('ix_embeddings_owner_id'), 'embeddings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_embeddings_project_id'), 'embeddings', ['project_id'], unique=False)
    op.create_index('ix_embeddings_stale', 'embeddings', ['project_id', 'stale'], unique=False)
    op.create_index(op.f('ix_embeddings_tenant_id'), 'embeddings', ['tenant_id'], unique=False)
    op.create_table('kg_nodes',
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kg_nodes')),
    sa.UniqueConstraint('project_id', 'type', 'ref_id', name='uq_kg_nodes_project_type_ref')
    )
    op.create_index('ix_kg_nodes_label_trgm', 'kg_nodes', ['label'], unique=False, postgresql_using='gin', postgresql_ops={'label': 'gin_trgm_ops'})
    op.create_index(op.f('ix_kg_nodes_project_id'), 'kg_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_kg_nodes_tenant_id'), 'kg_nodes', ['tenant_id'], unique=False)
    op.create_index('ix_kg_nodes_tsv', 'kg_nodes', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_kg_nodes_type', 'kg_nodes', ['project_id', 'type'], unique=False)
    op.create_table('kg_edges',
    sa.Column('src', sa.UUID(), nullable=False),
    sa.Column('dst', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst'], ['kg_nodes.id'], name=op.f('fk_kg_edges_dst_kg_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src'], ['kg_nodes.id'], name=op.f('fk_kg_edges_src_kg_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kg_edges')),
    sa.UniqueConstraint('src', 'dst', 'relation', name='uq_kg_edges_src_dst_rel')
    )
    op.create_index('ix_kg_edges_dst', 'kg_edges', ['dst', 'relation'], unique=False)
    op.create_index(op.f('ix_kg_edges_project_id'), 'kg_edges', ['project_id'], unique=False)
    op.create_index('ix_kg_edges_src', 'kg_edges', ['src', 'relation'], unique=False)
    op.create_index(op.f('ix_kg_edges_tenant_id'), 'kg_edges', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for t in _T:
        rls_enable(t, project_scoped=True)
    for t in _TENANT:
        rls_enable(t, project_scoped=False)


def downgrade() -> None:
    for t in _T + _TENANT:
        op.execute(f"DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}")
        op.execute(f"ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kg_edges_tenant_id'), table_name='kg_edges')
    op.drop_index('ix_kg_edges_src', table_name='kg_edges')
    op.drop_index(op.f('ix_kg_edges_project_id'), table_name='kg_edges')
    op.drop_index('ix_kg_edges_dst', table_name='kg_edges')
    op.drop_table('kg_edges')
    op.drop_index('ix_kg_nodes_type', table_name='kg_nodes')
    op.drop_index('ix_kg_nodes_tsv', table_name='kg_nodes', postgresql_using='gin')
    op.drop_index(op.f('ix_kg_nodes_tenant_id'), table_name='kg_nodes')
    op.drop_index(op.f('ix_kg_nodes_project_id'), table_name='kg_nodes')
    op.drop_index('ix_kg_nodes_label_trgm', table_name='kg_nodes', postgresql_using='gin', postgresql_ops={'label': 'gin_trgm_ops'})
    op.drop_table('kg_nodes')
    op.drop_index(op.f('ix_embeddings_tenant_id'), table_name='embeddings')
    op.drop_index('ix_embeddings_stale', table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_project_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_owner_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_embedding_jobs_tenant_id'), table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_project_id'), table_name='embedding_jobs')
    op.drop_table('embedding_jobs')
    # ### end Alembic commands ###
