"""0007 opportunities

Revision ID: 923521d86e85
Revises: 8237b61bf68a
Create Date: 2026-09-06 19:03:36.957388
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = '923521d86e85'
down_revision: str | None = '8237b61bf68a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('normalized_key', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_pattern', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('seo_impact', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('feasibility', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('risk', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('priority', sa.String(length=2), nullable=False),
    sa.Column('action_class', sa.String(length=28), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('proposed_change', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('verification_method', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detector', sa.String(length=40), nullable=False),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('project_id', 'normalized_key', name='uq_opportunities_project_key')
    )
    op.create_index('ix_opportunities_priority', 'opportunities', ['project_id', 'priority', 'status'], unique=False)
    op.create_index(op.f('ix_opportunities_project_id'), 'opportunities', ['project_id'], unique=False)
    op.create_index(op.f('ix_opportunities_tenant_id'), 'opportunities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    # ### end Alembic commands ###
    rls_enable("opportunities", project_scoped=True)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS opportunities_tenant_isolation ON opportunities")
    op.execute("ALTER TABLE opportunities NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE opportunities DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_tenant_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_project_id'), table_name='opportunities')
    op.drop_index('ix_opportunities_priority', table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
