"""0002 crawl + tool_calls

Revision ID: bb27d509590e
Revises: f95c40f1a6d8
Create Date: 2026-09-06 17:58:45.605563
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = 'bb27d509590e'
down_revision: str | None = 'f95c40f1a6d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TENANT_TABLES = ["tool_calls"]
_PROJECT_TABLES = ["crawl_runs", "page_snapshots", "crawl_results"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('tool_version', sa.String(length=20), nullable=False),
    sa.Column('caller', sa.String(length=60), nullable=True),
    sa.Column('risk', sa.String(length=24), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('llm_role', sa.String(length=16), nullable=True),
    sa.Column('llm_provider', sa.String(length=40), nullable=True),
    sa.Column('llm_model', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_correlation_id'), 'tool_calls', ['correlation_id'], unique=False)
    op.create_index('ix_tool_calls_created', 'tool_calls', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tool_calls_project_id'), 'tool_calls', ['project_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tenant_id'), 'tool_calls', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool'), 'tool_calls', ['tool'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('tier_requested', sa.String(length=12), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_crawl_runs_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs'))
    )
    op.create_index(op.f('ix_crawl_runs_project_id'), 'crawl_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_tenant_id'), 'crawl_runs', ['tenant_id'], unique=False)
    op.create_index('ix_crawl_runs_tenant_project', 'crawl_runs', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_website_id'), 'crawl_runs', ['website_id'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('crawl_run_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=12), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_key', sa.Text(), nullable=True),
    sa.Column('rendered_key', sa.Text(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], name=op.f('fk_page_snapshots_crawl_run_id_crawl_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_snapshots')),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_page_snapshots_hash')
    )
    op.create_index(op.f('ix_page_snapshots_crawl_run_id'), 'page_snapshots', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_page_snapshots_project_id'), 'page_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_page_snapshots_tenant_id'), 'page_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_page_snapshots_url', 'page_snapshots', ['project_id', 'url_hash'], unique=False)
    op.create_table('crawl_results',
    sa.Column('crawl_run_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical', sa.Text(), nullable=True),
    sa.Column('robots_meta', sa.String(length=120), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('internal_links', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('external_links', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('schema_blocks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('hreflang', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('changed_since_last', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], name=op.f('fk_crawl_results_crawl_run_id_crawl_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['page_snapshots.id'], name=op.f('fk_crawl_results_snapshot_id_page_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_results')),
    sa.UniqueConstraint('crawl_run_id', 'url_hash', name='uq_crawl_results_run_url')
    )
    op.create_index(op.f('ix_crawl_results_crawl_run_id'), 'crawl_results', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_crawl_results_project_id'), 'crawl_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_crawl_results_tenant_id'), 'crawl_results', ['tenant_id'], unique=False)
    op.create_index('ix_crawl_results_tenant_project', 'crawl_results', ['tenant_id', 'project_id'], unique=False)
    # ### end Alembic commands ###

    for table in _TENANT_TABLES:
        rls_enable(table, project_scoped=False)
    for table in _PROJECT_TABLES:
        rls_enable(table, project_scoped=True)


def downgrade() -> None:
    for table in [*_TENANT_TABLES, *_PROJECT_TABLES]:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crawl_results_tenant_project', table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_tenant_id'), table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_project_id'), table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_crawl_run_id'), table_name='crawl_results')
    op.drop_table('crawl_results')
    op.drop_index('ix_page_snapshots_url', table_name='page_snapshots')
    op.drop_index(op.f('ix_page_snapshots_tenant_id'), table_name='page_snapshots')
    op.drop_index(op.f('ix_page_snapshots_project_id'), table_name='page_snapshots')
    op.drop_index(op.f('ix_page_snapshots_crawl_run_id'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_crawl_runs_website_id'), table_name='crawl_runs')
    op.drop_index('ix_crawl_runs_tenant_project', table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_tenant_id'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_project_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_tool_calls_tool'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_tenant_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_project_id'), table_name='tool_calls')
    op.drop_index('ix_tool_calls_created', table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_correlation_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
