"""0011 ops

Revision ID: c7b68f2e41b5
Revises: ea2b5ef6ecc0
Create Date: 2026-09-06 19:58:43.649664
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = 'c7b68f2e41b5'
down_revision: str | None = 'ea2b5ef6ecc0'
branch_labels: str | Sequence[str] | None = None
_TENANT = ["dead_letter_events", "schedules", "agent_runs"]
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_correlation_id'), 'agent_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index('ix_agent_runs_state', 'agent_runs', ['tenant_id', 'state'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_table('dead_letter_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('consumer', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('replayed', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_events'))
    )
    op.create_index(op.f('ix_dead_letter_events_event_id'), 'dead_letter_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_events_tenant_id'), 'dead_letter_events', ['tenant_id'], unique=False)
    op.create_table('schedules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('tenant_id', 'project_id', 'name', name='uq_schedules_key')
    )
    op.create_index('ix_schedules_due', 'schedules', ['enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for t in _TENANT:
        rls_enable(t, project_scoped=False)


def downgrade() -> None:
    for t in _TENANT:
        op.execute(f'DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}')
        op.execute(f'ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {t} DISABLE ROW LEVEL SECURITY')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_index('ix_schedules_due', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_dead_letter_events_tenant_id'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_event_id'), table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_state', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_correlation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
