"""0010 geo

Revision ID: ea2b5ef6ecc0
Revises: 3f086c93a575
Create Date: 2026-09-06 19:54:55.132038
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = 'ea2b5ef6ecc0'
down_revision: str | None = '3f086c93a575'
branch_labels: str | Sequence[str] | None = None
_T = ["ai_prompts", "ai_prompt_runs", "ai_responses", "ai_citations", "ai_visibility_scores"]
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompts',
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_prompts')),
    sa.UniqueConstraint('project_id', 'kind', 'text_hash', name='uq_ai_prompts_key')
    )
    op.create_index(op.f('ix_ai_prompts_cluster_id'), 'ai_prompts', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_ai_prompts_project_id'), 'ai_prompts', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_prompts_tenant_id'), 'ai_prompts', ['tenant_id'], unique=False)
    op.create_table('ai_visibility_scores',
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('week', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('brand_mention_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('own_citation_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('prompts_run', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_visibility_scores')),
    sa.UniqueConstraint('project_id', 'cluster_id', 'provider', 'week', name='uq_ai_visibility_key')
    )
    op.create_index(op.f('ix_ai_visibility_scores_project_id'), 'ai_visibility_scores', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_visibility_scores_tenant_id'), 'ai_visibility_scores', ['tenant_id'], unique=False)
    op.create_table('ai_prompt_runs',
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser', sa.String(length=80), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], name=op.f('fk_ai_prompt_runs_prompt_id_ai_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_prompt_runs'))
    )
    op.create_index(op.f('ix_ai_prompt_runs_project_id'), 'ai_prompt_runs', ['project_id'], unique=False)
    op.create_index('ix_ai_prompt_runs_prompt', 'ai_prompt_runs', ['prompt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_prompt_runs_tenant_id'), 'ai_prompt_runs', ['tenant_id'], unique=False)
    op.create_table('ai_citations',
    sa.Column('prompt_run_id', sa.UUID(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('brand_position', sa.Integer(), nullable=True),
    sa.Column('competitors_mentioned', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cited_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('own_url_cited', sa.Boolean(), nullable=False),
    sa.Column('sentiment', sa.String(length=12), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['ai_prompt_runs.id'], name=op.f('fk_ai_citations_prompt_run_id_ai_prompt_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_citations'))
    )
    op.create_index(op.f('ix_ai_citations_project_id'), 'ai_citations', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_citations_prompt_run_id'), 'ai_citations', ['prompt_run_id'], unique=False)
    op.create_index(op.f('ix_ai_citations_tenant_id'), 'ai_citations', ['tenant_id'], unique=False)
    op.create_table('ai_responses',
    sa.Column('prompt_run_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_key', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['ai_prompt_runs.id'], name=op.f('fk_ai_responses_prompt_run_id_ai_prompt_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_responses'))
    )
    op.create_index(op.f('ix_ai_responses_project_id'), 'ai_responses', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_responses_prompt_run_id'), 'ai_responses', ['prompt_run_id'], unique=False)
    op.create_index(op.f('ix_ai_responses_tenant_id'), 'ai_responses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for t in _T:
        rls_enable(t, project_scoped=True)


def downgrade() -> None:
    for t in _T:
        op.execute(f'DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}')
        op.execute(f'ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {t} DISABLE ROW LEVEL SECURITY')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_responses_tenant_id'), table_name='ai_responses')
    op.drop_index(op.f('ix_ai_responses_prompt_run_id'), table_name='ai_responses')
    op.drop_index(op.f('ix_ai_responses_project_id'), table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index(op.f('ix_ai_citations_tenant_id'), table_name='ai_citations')
    op.drop_index(op.f('ix_ai_citations_prompt_run_id'), table_name='ai_citations')
    op.drop_index(op.f('ix_ai_citations_project_id'), table_name='ai_citations')
    op.drop_table('ai_citations')
    op.drop_index(op.f('ix_ai_prompt_runs_tenant_id'), table_name='ai_prompt_runs')
    op.drop_index('ix_ai_prompt_runs_prompt', table_name='ai_prompt_runs')
    op.drop_index(op.f('ix_ai_prompt_runs_project_id'), table_name='ai_prompt_runs')
    op.drop_table('ai_prompt_runs')
    op.drop_index(op.f('ix_ai_visibility_scores_tenant_id'), table_name='ai_visibility_scores')
    op.drop_index(op.f('ix_ai_visibility_scores_project_id'), table_name='ai_visibility_scores')
    op.drop_table('ai_visibility_scores')
    op.drop_index(op.f('ix_ai_prompts_tenant_id'), table_name='ai_prompts')
    op.drop_index(op.f('ix_ai_prompts_project_id'), table_name='ai_prompts')
    op.drop_index(op.f('ix_ai_prompts_cluster_id'), table_name='ai_prompts')
    op.drop_table('ai_prompts')
    # ### end Alembic commands ###
