"""0013_oauth_credentials

Revision ID: f6f34c89b75f
Revises: 81470a3a36a8
Create Date: 2026-09-13 00:26:09.324178
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = 'f6f34c89b75f'
down_revision: str | None = '81470a3a36a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLES = ["oauth_credentials"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_credentials',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('connected_by', sa.UUID(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('provider_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('google')", name=op.f('ck_oauth_credentials_provider_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_credentials'))
    )
    op.create_index(op.f('ix_oauth_credentials_project_id'), 'oauth_credentials', ['project_id'], unique=False)
    op.create_index('ix_oauth_credentials_project_provider', 'oauth_credentials', ['project_id', 'provider'], unique=False)
    op.create_index(op.f('ix_oauth_credentials_tenant_id'), 'oauth_credentials', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for table in _TABLES:
        rls_enable(table, project_scoped=True)


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_credentials_tenant_id'), table_name='oauth_credentials')
    op.drop_index('ix_oauth_credentials_project_provider', table_name='oauth_credentials')
    op.drop_index(op.f('ix_oauth_credentials_project_id'), table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    # ### end Alembic commands ###
