"""0004 keywords + serp

Revision ID: f8e77c101179
Revises: 29338c6c7573
Create Date: 2026-09-06 18:42:16.230100
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

_PROJECT_TABLES = [
    "keyword_clusters", "keywords", "search_intents", "keyword_page_map",
    "serp_runs", "serp_results", "serp_features", "serp_entities",
]

revision: str = 'f8e77c101179'
down_revision: str | None = '29338c6c7573'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_clusters',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('volume_sum', sa.Integer(), nullable=False),
    sa.Column('primary_intent', sa.String(length=20), nullable=True),
    sa.Column('intents', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_clusters')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_keyword_clusters_project_slug')
    )
    op.create_index(op.f('ix_keyword_clusters_project_id'), 'keyword_clusters', ['project_id'], unique=False)
    op.create_index(op.f('ix_keyword_clusters_tenant_id'), 'keyword_clusters', ['tenant_id'], unique=False)
    op.create_table('serp_runs',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('device', sa.String(length=8), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_key', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_runs'))
    )
    op.create_index(op.f('ix_serp_runs_keyword_id'), 'serp_runs', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_serp_runs_project_id'), 'serp_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_serp_runs_tenant_id'), 'serp_runs', ['tenant_id'], unique=False)
    op.create_index('ix_serp_runs_tenant_project', 'serp_runs', ['tenant_id', 'project_id'], unique=False)
    op.create_table('keywords',
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('normalized', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('volume_estimated', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('difficulty_estimated', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], name=op.f('fk_keywords_cluster_id_keyword_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('project_id', 'normalized', name='uq_keywords_project_norm')
    )
    op.create_index(op.f('ix_keywords_cluster_id'), 'keywords', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_index(op.f('ix_keywords_tenant_id'), 'keywords', ['tenant_id'], unique=False)
    op.create_index('ix_keywords_tenant_project', 'keywords', ['tenant_id', 'project_id'], unique=False)
    op.create_table('serp_entities',
    sa.Column('serp_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['serp_run_id'], ['serp_runs.id'], name=op.f('fk_serp_entities_serp_run_id_serp_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_entities'))
    )
    op.create_index(op.f('ix_serp_entities_project_id'), 'serp_entities', ['project_id'], unique=False)
    op.create_index(op.f('ix_serp_entities_serp_run_id'), 'serp_entities', ['serp_run_id'], unique=False)
    op.create_index(op.f('ix_serp_entities_tenant_id'), 'serp_entities', ['tenant_id'], unique=False)
    op.create_table('serp_features',
    sa.Column('serp_run_id', sa.UUID(), nullable=False),
    sa.Column('feature_type', sa.String(length=24), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['serp_run_id'], ['serp_runs.id'], name=op.f('fk_serp_features_serp_run_id_serp_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_features'))
    )
    op.create_index(op.f('ix_serp_features_project_id'), 'serp_features', ['project_id'], unique=False)
    op.create_index(op.f('ix_serp_features_serp_run_id'), 'serp_features', ['serp_run_id'], unique=False)
    op.create_index(op.f('ix_serp_features_tenant_id'), 'serp_features', ['tenant_id'], unique=False)
    op.create_table('serp_results',
    sa.Column('serp_run_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('is_own', sa.Boolean(), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['serp_run_id'], ['serp_runs.id'], name=op.f('fk_serp_results_serp_run_id_serp_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_results')),
    sa.UniqueConstraint('serp_run_id', 'position', name='uq_serp_results_run_pos')
    )
    op.create_index('ix_serp_results_domain', 'serp_results', ['project_id', 'domain'], unique=False)
    op.create_index(op.f('ix_serp_results_project_id'), 'serp_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_serp_results_serp_run_id'), 'serp_results', ['serp_run_id'], unique=False)
    op.create_index(op.f('ix_serp_results_tenant_id'), 'serp_results', ['tenant_id'], unique=False)
    op.create_table('keyword_page_map',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_page_map_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_page_map')),
    sa.UniqueConstraint('keyword_id', 'url_hash', name='uq_keyword_page_map_kw_url')
    )
    op.create_index('ix_keyword_page_map_kw', 'keyword_page_map', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_page_map_project_id'), 'keyword_page_map', ['project_id'], unique=False)
    op.create_index(op.f('ix_keyword_page_map_tenant_id'), 'keyword_page_map', ['tenant_id'], unique=False)
    op.create_table('search_intents',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_search_intents_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_intents')),
    sa.UniqueConstraint('keyword_id', 'label', name='uq_search_intents_keyword_label')
    )
    op.create_index(op.f('ix_search_intents_keyword_id'), 'search_intents', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_search_intents_project_id'), 'search_intents', ['project_id'], unique=False)
    op.create_index(op.f('ix_search_intents_tenant_id'), 'search_intents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    for t in _PROJECT_TABLES:
        rls_enable(t, project_scoped=True)


def downgrade() -> None:
    for t in _PROJECT_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {t}_tenant_isolation ON {t}")
        op.execute(f"ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_intents_tenant_id'), table_name='search_intents')
    op.drop_index(op.f('ix_search_intents_project_id'), table_name='search_intents')
    op.drop_index(op.f('ix_search_intents_keyword_id'), table_name='search_intents')
    op.drop_table('search_intents')
    op.drop_index(op.f('ix_keyword_page_map_tenant_id'), table_name='keyword_page_map')
    op.drop_index(op.f('ix_keyword_page_map_project_id'), table_name='keyword_page_map')
    op.drop_index('ix_keyword_page_map_kw', table_name='keyword_page_map')
    op.drop_table('keyword_page_map')
    op.drop_index(op.f('ix_serp_results_tenant_id'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_serp_run_id'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_project_id'), table_name='serp_results')
    op.drop_index('ix_serp_results_domain', table_name='serp_results')
    op.drop_table('serp_results')
    op.drop_index(op.f('ix_serp_features_tenant_id'), table_name='serp_features')
    op.drop_index(op.f('ix_serp_features_serp_run_id'), table_name='serp_features')
    op.drop_index(op.f('ix_serp_features_project_id'), table_name='serp_features')
    op.drop_table('serp_features')
    op.drop_index(op.f('ix_serp_entities_tenant_id'), table_name='serp_entities')
    op.drop_index(op.f('ix_serp_entities_serp_run_id'), table_name='serp_entities')
    op.drop_index(op.f('ix_serp_entities_project_id'), table_name='serp_entities')
    op.drop_table('serp_entities')
    op.drop_index('ix_keywords_tenant_project', table_name='keywords')
    op.drop_index(op.f('ix_keywords_tenant_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_cluster_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('ix_serp_runs_tenant_project', table_name='serp_runs')
    op.drop_index(op.f('ix_serp_runs_tenant_id'), table_name='serp_runs')
    op.drop_index(op.f('ix_serp_runs_project_id'), table_name='serp_runs')
    op.drop_index(op.f('ix_serp_runs_keyword_id'), table_name='serp_runs')
    op.drop_table('serp_runs')
    op.drop_index(op.f('ix_keyword_clusters_tenant_id'), table_name='keyword_clusters')
    op.drop_index(op.f('ix_keyword_clusters_project_id'), table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    # ### end Alembic commands ###
