"""0001 foundation

Revision ID: f95c40f1a6d8
Revises: 
Create Date: 2026-09-06 15:41:23.216928
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from db.rls import enable as rls_enable

revision: str = 'f95c40f1a6d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tenant-scoped tables get RLS keyed on tenant_id. `tenants` keys on `id`. The three
# identity-global config tables (users, prompt_templates, agent_versions) are excluded — see
# docs/SECURITY.md.
_TENANT_TABLES = [
    "memberships", "projects", "audit_logs", "outbox_events", "processed_events",
    "resource_locks", "job_runs", "model_registry",
]
_PROJECT_TABLES = ["websites", "urls", "pages", "evidence", "evidence_links"]
_GLOBAL_TABLES = ["users", "prompt_templates", "agent_versions"]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('model_role', sa.String(length=16), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent', 'version', name='uq_agent_versions_agent_version')
    )
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_subject_id'), 'audit_logs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('evidence',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('crawl_run_id', sa.UUID(), nullable=True),
    sa.Column('serp_run_id', sa.UUID(), nullable=True),
    sa.Column('ai_prompt_run_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('parser', sa.String(length=80), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('http_response', 'rendered_dom', 'gsc_row', 'ga4_row', 'serp_snapshot', 'ai_response', 'sitemap', 'robots', 'pagespeed', 'rich_results', 'competitor_snapshot', 'log_line')", name=op.f('ck_evidence_kind_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('tenant_id', 'content_hash', 'kind', name='uq_evidence_hash_kind')
    )
    op.create_index(op.f('ix_evidence_ai_prompt_run_id'), 'evidence', ['ai_prompt_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_crawl_run_id'), 'evidence', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_serp_run_id'), 'evidence', ['serp_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_job_runs_idempotency_key')
    )
    op.create_index(op.f('ix_job_runs_job_type'), 'job_runs', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_runs_tenant_id'), 'job_runs', ['tenant_id'], unique=False)
    op.create_table('model_registry',
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('fallbacks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry')),
    sa.UniqueConstraint('tenant_id', 'role', name='uq_model_registry_tenant_role')
    )
    op.create_index(op.f('ix_model_registry_tenant_id'), 'model_registry', ['tenant_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_outbox_events_event_id'))
    )
    op.create_index(op.f('ix_outbox_events_correlation_id'), 'outbox_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_project_id'), 'outbox_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_published_at'), 'outbox_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_type'), 'outbox_events', ['type'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('consumer', sa.String(length=120), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_events')),
    sa.UniqueConstraint('event_id', 'consumer', name='uq_processed_events_event_consumer')
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_processed_events_tenant_id'), 'processed_events', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('business_goal', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('approval_mode', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_projects_tenant_slug')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_templates_name_version')
    )
    op.create_table('resource_locks',
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('holder_run_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_locks')),
    sa.UniqueConstraint('resource_type', 'resource_id', name='uq_resource_locks_resource')
    )
    op.create_index(op.f('ix_resource_locks_tenant_id'), 'resource_locks', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('supabase_uid', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('supabase_uid', name=op.f('uq_users_supabase_uid'))
    )
    op.create_table('websites',
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('cms_type', sa.String(length=40), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites')),
    sa.UniqueConstraint('project_id', 'origin', name='uq_websites_project_origin')
    )
    op.create_index(op.f('ix_websites_project_id'), 'websites', ['project_id'], unique=False)
    op.create_index(op.f('ix_websites_tenant_id'), 'websites', ['tenant_id'], unique=False)
    op.create_table('evidence_links',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("subject_type IN ('issue', 'opportunity', 'recommendation', 'kg_edge', 'agent_decision', 'verification', 'learning')", name=op.f('ck_evidence_links_subject_type_allowed')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_evidence_links_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_links')),
    sa.UniqueConstraint('evidence_id', 'subject_type', 'subject_id', name='uq_evidence_link_subject')
    )
    op.create_index(op.f('ix_evidence_links_evidence_id'), 'evidence_links', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_project_id'), 'evidence_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_subject_id'), 'evidence_links', ['subject_id'], unique=False)
    op.create_index(op.f('ix_evidence_links_tenant_id'), 'evidence_links', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_memberships_tenant_user')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('urls',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_run', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_urls_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_urls')),
    sa.UniqueConstraint('project_id', 'url_hash', name='uq_urls_project_hash')
    )
    op.create_index(op.f('ix_urls_project_id'), 'urls', ['project_id'], unique=False)
    op.create_index(op.f('ix_urls_tenant_id'), 'urls', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_urls_website_id'), 'urls', ['website_id'], unique=False)
    op.create_table('pages',
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('last_crawled_run', sa.UUID(), nullable=True),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], name=op.f('fk_pages_url_id_urls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_pages_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('project_id', 'url_id', name='uq_pages_project_url')
    )
    op.create_index(op.f('ix_pages_project_id'), 'pages', ['project_id'], unique=False)
    op.create_index(op.f('ix_pages_tenant_id'), 'pages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pages_url_id'), 'pages', ['url_id'], unique=False)
    op.create_index(op.f('ix_pages_website_id'), 'pages', ['website_id'], unique=False)
    # ### end Alembic commands ###

    # Composite indexes leading with tenant/project (A-TO-Z-PLAN.md §F.5).
    op.create_index("ix_projects_tenant_slug", "projects", ["tenant_id", "slug"])
    op.create_index("ix_websites_tenant_project", "websites", ["tenant_id", "project_id"])
    op.create_index("ix_pages_tenant_project", "pages", ["tenant_id", "project_id"])
    op.create_index("ix_urls_tenant_project", "urls", ["tenant_id", "project_id"])
    op.create_index("ix_evidence_tenant_project", "evidence", ["tenant_id", "project_id"])
    op.create_index(
        "ix_outbox_unpublished", "outbox_events", ["created_at"],
        postgresql_where=sa.text("published_at IS NULL"),
    )

    # ── Row-Level Security (A-TO-Z-PLAN.md §F.2) ──────────────────────────────
    # tenants: a tenant may read only its own row.
    op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenants_self_isolation ON tenants "
        "USING (id = current_setting('app.tenant_id', true)::uuid) "
        "WITH CHECK (id = current_setting('app.tenant_id', true)::uuid)"
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON tenants TO seo_app")
    op.execute("GRANT SELECT ON tenants TO seo_readonly")

    for table in _TENANT_TABLES:
        rls_enable(table, project_scoped=False)
    for table in _PROJECT_TABLES:
        rls_enable(table, project_scoped=True)

    # Identity-global config tables: no RLS, plain grants.
    for table in _GLOBAL_TABLES:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO seo_app")
        op.execute(f"GRANT SELECT ON {table} TO seo_readonly")


def downgrade() -> None:
    for table in ["tenants", *_TENANT_TABLES, *_PROJECT_TABLES]:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")
        op.execute(f"DROP POLICY IF EXISTS {table}_self_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    for name, tbl in [
        ("ix_projects_tenant_slug", "projects"), ("ix_websites_tenant_project", "websites"),
        ("ix_pages_tenant_project", "pages"), ("ix_urls_tenant_project", "urls"),
        ("ix_evidence_tenant_project", "evidence"), ("ix_outbox_unpublished", "outbox_events"),
    ]:
        op.drop_index(name, table_name=tbl)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_website_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_url_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_tenant_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_project_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_urls_website_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_tenant_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_project_id'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_evidence_links_tenant_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_subject_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_project_id'), table_name='evidence_links')
    op.drop_index(op.f('ix_evidence_links_evidence_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_websites_tenant_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_project_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_resource_locks_tenant_id'), table_name='resource_locks')
    op.drop_table('resource_locks')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_processed_events_tenant_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_outbox_events_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_published_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_project_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_correlation_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_model_registry_tenant_id'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_job_runs_tenant_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_type'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_serp_run_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_crawl_run_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_ai_prompt_run_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_subject_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('agent_versions')
    # ### end Alembic commands ###
